### ISSUE TITLE
Keycloack crashes upon given parameters of the client application

### ISSUE THREAD

**Issue by francis-pouatcha** [adorsys/keycloak-ssi-deployment#48]

**Comment by Marcjazz** [comment]
2024-06-28 07:51:01,385 INFO  [io.quarkus] (main) Profile prod activated. 
2024-06-28 07:51:01,385 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-postgresql, keycloak, logging-gelf, narayana-jta, reactive-routes, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, vertx]
2024-06-28 07:51:46,461 ERROR [org.keycloak.headers.DefaultSecurityHeadersProvider] (executor-thread-2) MediaType not set on path /realms/master/protocol/oid4vc/credential-offer-uri, with response status 400
2024-06-28 07:51:46,474 ERROR [io.quarkus.vertx.http.runtime.QuarkusErrorHandler] (executor-thread-2) HTTP Request to /realms/master/protocol/oid4vc/credential-offer-uri?credential_configuration_id=test-credential failed, error id: f549bb1f-73aa-44bd-b93d-a08e30cd1434-1: jakarta.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
        at org.keycloak.headers.DefaultSecurityHeadersProvider.addHeaders(DefaultSecurityHeadersProvider.java:75)
        at org.keycloak.services.filters.KeycloakSecurityHeadersFilter.filter(KeycloakSecurityHeadersFilter.java:45)
        at org.jboss.resteasy.reactive.server.handlers.ResourceResponseFilterHandler.handle(ResourceResponseFilterHandler.java:25)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)

2024-06-28 07:53:15,310 WARN  [org.keycloak.protocol.oidc.utils.OAuth2CodeParser] (executor-thread-2) Code '2bedca60-0bbd-4e13-9f3e-29fc59bfcf34' already used for userSession 'b2a790df-2b46-4701-8395-1c1a904fdb89' and client '2c296106-9a17-4341-9c18-874ecd7ee142'.
2024-06-28 07:53:15,313 WARN  [org.keycloak.events] (executor-thread-2) type="CODE_TO_TOKEN_ERROR", realmId="61b69eb3-b712-4ca9-89c0-ae118ed1cf06", realmName="master", clientId="null", userId="null", sessionId="b2a790df-2b46-4701-8395-1c1a904fdb89", ipAddress="13.60.75.176", error="invalid_code", grant_type="urn:ietf:params:oauth:grant-type:pre-authorized_code", code_id="b2a790df-2b46-4701-8395-1c1a904fdb89"
